### PR TITLE
P1 snackbar

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
Added toast. Can view the same here: https://deploy-preview-8--thisui.netlify.app/molecules/toast/

### CODE REVIEW

**Review by mdarif6 — APPROVED** [review]
seems fine

**Review by Hnh013 — APPROVED** [review]
code looks good , convention is properly followed

**Review by samyakshah3008 — APPROVED** [review]
LGTM

**Comment by SJTGSHIVAM** [comment]
As I see two positive reviews I will be merging it now.

**Pull request merged**
