### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
https://deploy-preview-6--thisui.netlify.app/molecules/navbar
here is the link to the design

### CODE REVIEW

**Review by SJTGSHIVAM — COMMENTED** [review]
entry point is missing.

**Comment by SJTGSHIVAM** [comment]
Added the entry point as well.

**Comment by SJTGSHIVAM** [comment]
Fixed the missing code issue

**Review by mdarif6 — APPROVED** [review]
This one also fine

**Review by Hnh013 — COMMENTED** [review]
navbar looks good enough to approve and merge, BEM classes convention is also good

**Review by Hnh013 — APPROVED** [review]

**Review by samyakshah3008 — APPROVED** [review]
Looks good to merge!

**Review by romabulani — COMMENTED** [review]
image
Code is clean.
Once, check the css style for nav bar.

**Comment by SJTGSHIVAM** [comment]
@romabulani  I have fixed the issues as per the discussion and also made the navbar responsive.it still won't look good at all the device sizes at the time of display as it has half the with of screen size.

**Comment by romabulani** [comment]
> @romabulani I have fixed the issues as per the discussion and also made the navbar responsive.it still won't look good at all the device sizes at the time of display as it has half the with of screen size.

Yes it looks good now, good to merge

**Comment by SJTGSHIVAM** [comment]
romabulani thanks for the approval I merged it as discussed.

**Pull request merged**
