### PR TITLE
P0 card

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
Add: card component
    
    - fixed soem errors in the older components
    - added new parts to badge component
    - Add: Ribbion Badges
    - added card component
    - added differnt utility classes that were needed
    - Add: sharing link

### CODE REVIEW

**Review by varnita619 — APPROVED** [review]
Looks good

**Review by mdarif6 — APPROVED** [review]
Please check Horizontal  Card one, text is overlapping

**Review by samyakshah3008 — APPROVED** [review]
Looks good to merge! 
Make sure to check your horizontal card again

**Comment by SJTGSHIVAM** [comment]
image
image
I don't see any issues at my end do you see any abnormal behaviour please share

**Comment by SJTGSHIVAM** [comment]
I figured out this was an issue due to default min-height property of gird have made the required fixes now things are fine.
Thanks for pointing out @mdarif6 @samyakshah3008

**Pull request merged**
